# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        # PYTHON_PATH: Api_Projet7/app.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        #python -m install -e requirements.txt
        pip install --ignore-installed -r requirements.txt
        #if [ -f requirements.txt ]; then pip install -e requirements.txt; fi
    - name: Test with pytest
      run: |
         pytest PytestP7.py
         
    - name: Add remote origin
      if: github.ref == 'refs/heads/main' && job.status == 'success' #nous spécifions que cette action ne s'exécutera que si tout jusqu'à présent a réussi - donc s'il y a un échec dans les tests, alors cela ne sera pas déployés, then this will not be deployed.
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:main -f
